### ISSUE TITLE
Day 46 Django urls.py import include

### ISSUE THREAD

**Issue by ericchou1** [talkpython/100daysofweb-with-python-course#10]
Just a note, by default project urls.py did not import include method (at least for me when following the steps) so it needs to be explicitly imported. 

Default: 

from django.urls import path

Add:

from django.urls import path, include

**Comment by bbelderbos** [comment]
Thanks @ericchou1 is that in the video only? I do see it in the demo code: https://github.com/talkpython/100daysofweb-with-python-course/blob/master/days/045-048-django-intro/demo/mysite/urls.py

**Comment by ericchou1** [comment]
Yes, video only, I went back to the source code to see where include() should have been imported from, then saw it was django.urls.

**Comment by mikeckennedy** [comment]
Thanks for all the QA Eric. :)

**Comment by ericchou1** [comment]
Of course, thank you @bbelderbos @mikeckennedy and @hobojoe1848 for the great course. Learning a lot!

**Comment by bbelderbos** [comment]
@ericchou1 I just checked " URL routing and your first view" and the `include` is in there, was it another video perhaps? Cheers

**Comment by ericchou1** [comment]
You are right, I must have missed it in the first minute of the video. I will resolve this, thanks for checking!
