### ISSUE TITLE
Days 09-12 Building APIs with Api Star (0.5.x)

### ISSUE THREAD

**Issue by alex-vegan** [talkpython/100daysofweb-with-python-course#15]
009-012-modern-apis-starred/demo/app.py
for function create_car() we define car_id like len(cars)+1 but after first delete_car() it dosn't work!
isn't better to check max(cars.keys())+1 for same task, or something else?

**Comment by bbelderbos** [comment]
Hey @alex-vegan this indeed failed! https://github.com/talkpython/100daysofweb-with-python-course/commit/6262742556469b721b3ab2a6ae0c68976ef2ab87 - added a test and implemented your fix. Thanks!
