### ISSUE TITLE
Day 69-72 Django Rest Framework Swagger error

### ISSUE THREAD

**Issue by Joeriksson** [talkpython/100daysofweb-with-python-course#18]
After coding along the videos in this section of the course. I get a

`'AutoSchema' object has no attribute 'get_link'` error when going to api/docs.

It turns out you need to put the following into settings.py to get it to work

```
REST_FRAMEWORK = {
  'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}
```

Reference: https://www.django-rest-framework.org/community/3.10-announcement/#continuing-to-use-coreapi

It's probably because I am using a newer version of django-rest-framework than is used in the videos?

**Comment by bbelderbos** [comment]
Thanks for pointing this out @Joeriksson, I reproduced and fixed it as per above: https://github.com/talkpython/100daysofweb-with-python-course/commit/1aabe58bc29e5453d77dae96e24cb2c2adc2b3f7

**Comment by alex-vegan** [comment]
@Joeriksson, thanks for that. You've saved my time and nerves for find release of this issue.

**Comment by Joeriksson** [comment]
@alex-vegan glad it helped!
