### ISSUE TITLE
Days 9-12 - update Api Star documentation links

### ISSUE THREAD

**Issue by vyahello** [talkpython/100daysofweb-with-python-course#19]
While observing `README.md` file for `days 9-12` I can see that some API Star documentation links are obsolete (shows 404 error) e.g:
- https://docs.apistar.com/api-guide/type-system
- https://docs.apistar.com/api-guide/testing

Please update all Api Star links to make it more representative, thx!

**Comment by mikeckennedy** [comment]
Thanks @vyahello !

**Comment by bbelderbos** [comment]
Links updated and added a deprecation note around server / testing, thanks @vyahello

**Comment by vyahello** [comment]
awesome, thanks guys 👍
