### ISSUE TITLE
Days 93-100: @api.route ↑↑ shifts

### ISSUE THREAD

**Issue by alex-vegan** [talkpython/100daysofweb-with-python-course#22]
talkpython/100daysofweb-with-python-course/days/093-096-vuejs/movie_svc/views/api_views.py

talkpython/100daysofweb-with-python-course/days/097-100-docker/demo/services/movie_svc/views/api_views.py

@api.route("/api/movie/genre/all") should be placed upper ↑ than @api.route("/api/movie/genre/{genre}")

and 

@api.route("/api/movie/top") upper ↑ than @api.route("/api/movie/{imdb_number}")

**Comment by mikeckennedy** [comment]
Thanks Alex. I think this was a change in responder's interpretation of these routes. It worked in the demo I did, but I see now that it stopped. All fixed.
