### ISSUE TITLE
Question: double forward underscores 

### ISSUE THREAD

**Issue by vyahello** [talkpython/100daysofweb-with-python-course#30]
Hey guys, I'm pretty excited about your course and job you have done to make it, that's really thorough work.

But sometimes I'm getting a bit confused when seeing double underscores in functions/variables names in various 100DaysOfWeb chapters. 
I know that those are used as `super-private` objects or relative, but can you guys explain me as experts, what is reason to not use a single forward underscore as conventional privacy in python but use double underscores?
For instance, please take a look at a code snippet below (chapter 33-36). Can't we use just `self._result` name instead of `self.__result` here to mark that it should be a private one? 

```python
class switch:
    __no_result = uuid.uuid4()

    def __init__(self, value):
        self._found = False
        self.__result = switch.__no_result
```

Do you think it's worth to mention that somewhere in a course? thx

**Comment by mikeckennedy** [comment]
Hi, the reason we don't cover this deeply in the course is we are just reusing that [python-switch](https://github.com/mikeckennedy/python-switch) library from github. So we didn't discuss the internals. 

But the reason for __thing and why this is **better** than a convention of just _thing is that the runtime makes it truly hidden, not just devs thinking to themselves it should be hidden. For example:

`print(switch.__no_result)` will result in the error:

```
AttributeError: type object 'switch' has no attribute '__no_result'
```

That is **much** stronger just some convention that you might or might not know that you should not touch that.

cc @hobojoe1848 @bbelderbos
