### ISSUE TITLE
Days 37-40: Intro to Pyramid: Adding the data models

### ISSUE THREAD

**Issue by gloc-mike** [talkpython/100daysofweb-with-python-course#33]
In this section of the course, I **_copied_** the `bin`, `data` and `db` code from the 100 Days GitHub repo into my version of the code.

I found that in `data/db_session.py`, the return value needs to be the attribute `factory` i.e. `DbSession.factory`, rather than the method i.e. `DbSession.factory()`.

However, after fixing that issue, I am now confronted with another. In `bin/load_base_data.py`, the session returned does not have the 'query' attribute!

I created this Gist which shows the error: 
https://gist.github.com/gloc-mike/ddb4fb4ca0aa1ba81209623a8858d606.

When I review the `session` object in the debug console in PyCharm, I can see that  'query' appears in the `public_methods` tuple (see attached screenshot) but the my watch expression again, shows the attribute error.

![Screen Shot 2020-02-24 at 12 51 24](https://user-images.githubusercontent.com/2324626/75124592-6be6e080-5704-11ea-829e-71cf26aecb88.png)

 Any ideas to help me resolve this issue would be appreciated.

**Comment by gloc-mike** [comment]
My assumption is wrong i.e. _that `DbSession.factory()`needed to be refactored to `DbSession.factory`._ so I'm closing this issue.

My code works after reverting to `DbSession.factory()` but it is still very odd that it did not run when I first copied the data modelling modules into my project. Is there maybe a first run issue?

I'm still at a loss as to why my version was not working. When I was debugging it I could clearly see that the `DbSession.factory` attribute was set to `None` which is why it was originally failing but why should it suddenly start working after I revert my change above?

Anyway, I am closing this issue.

**Comment by mikeckennedy** [comment]
Hi @gloc-mike It definitely needs to be returning a Session. But I think the problem was it's returning `session_maker` not `session_maker()`. One is the function that makes sessions, the other is a particular session created by that function for the **Unit of Work**.

Hope that helps!
Michael

**Comment by gloc-mike** [comment]
Hi,

I created a new Pyramid project which I want to billed to track timesheet info and I am getting the original error (the error that occurred BEFORE the error I reported in this issue).

Please see the Gist I created:
https://gist.github.com/gloc-mike/fd84826f0c505be1e61f7f7493925bd0

I created the project using PyCharm for Pyramid. It was created with a lot of `jinja2` code so I removed that, added the bit and pieces from the course example i.e. `bin`, `data` and `db`, and modified the data model to suite the project.

Then I ran it and it failed with the value 'None' being returned from the `DbSession.factory()` call, which as I said before is the error I was originally having when I submitted this issue and in which I made some poor assumptions.

Anyway, THIS is the right error! ;) Have you seen this error before? Is it a first run type issue?

Here is the link to the project on GitHub:
https://github.com/gloc-mike/timesheets

Thanks for the help!
Michael

**Comment by mikeckennedy** [comment]
Hi, I responded to the issue in the gist.

**Comment by mikeckennedy** [comment]
Hi @gloc-mike There were quite a few issues with the repo. Here's a running version. Try doing a diff on the directories to see what changed. :)

https://send.firefox.com/download/406ddab5c4cabb0c/#iau8zBEX6mH9Bwbd5QOnxQ
