### ISSUE TITLE
Day 22. Installing requirements incompatible chardet

### ISSUE THREAD

**Issue by johniuro** [talkpython/100daysofweb-with-python-course#40]
aiohttp 3.7.3 requires chardet<4.0,>=2.0, but you'll have chardet 4.0.0 which is incompatible.

**Comment by bbelderbos** [comment]
Is that day 22? It seems the requirements are not pinned for the project folders that day.

**Comment by johniuro** [comment]
It is day 2, "your turn," of asyncio on flask

**Comment by bbelderbos** [comment]
The aysnc chapter is quart == days 21-24, day 2 there is unpinned:
https://github.com/talkpython/100daysofweb-with-python-course/blob/master/days/021-024-quart-async/your_turn/day_2/web_crawl/requirements.txt

Or do you mean day 2 of the course, the requirements are pinned there.

Thanks
Bob

**Comment by johniuro** [comment]
Correct, day 22 of the course, day 2 of the asynchio "your turn"

You are missing the issue,tho

yes the requirements.txt is there, but it hasn't been modified since 2018

when I pip install the requirements, I am alerted with a warning that says "aiohttp 3.7.3 requires chardet<4.0,>=2.0, but you'll have chardet 4.0.0 which is incompatible."

That is the issue

**Comment by bbelderbos** [comment]
Thanks @johniuro reproduced on my side: 

```
$ pip install -r requirements.txt
...
aiohttp 3.7.3 requires chardet<4.0,>=2.0, but you'll have chardet 4.0.0 which is incompatible.
``

@mikeckennedy as this is your chapter, do you want to pin the requirements?

**Comment by mikeckennedy** [comment]
Hi guys. @johniuro Sorry for the trouble. But I don't see the issue being with the `requirements.txt` file itself. I just created a new virtual environment and did a `pip install -r requirements.txt` on that file, contents:

```
requests
bs4
colorama
aiohttp
cchardet
```

And it installed fine:

```
Collecting aiohttp
  Using cached aiohttp-3.7.3-cp39-cp39-macosx_10_14_x86_64.whl (648 kB)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting attrs>=17.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting chardet<4.0,>=2.0
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-5.1.0-cp39-cp39-macosx_10_14_x86_64.whl (49 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.6.3-cp39-cp39-macosx_10_14_x86_64.whl (124 kB)
Collecting idna>=2.0
  Downloading idna-3.1-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 1.8 MB/s 
Collecting bs4
  Using cached bs4-0.0.1-py3-none-any.whl
Collecting cchardet
  Downloading cchardet-2.1.7-cp39-cp39-macosx_10_9_x86_64.whl (124 kB)
     |████████████████████████████████| 124 kB 2.4 MB/s 
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna>=2.0
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.1-py3-none-any.whl (32 kB)
Installing collected packages: soupsieve, multidict, idna, yarl, urllib3, typing-extensions, 
chardet, certifi, beautifulsoup4, attrs, async-timeout, requests, colorama, cchardet, 
bs4, aiohttp
Successfully installed aiohttp-3.7.3 async-timeout-3.0.1 attrs-20.3.0 
beautifulsoup4-4.9.3 bs4-0.0.1 cchardet-2.1.7 certifi-2020.12.5 chardet-3.0.4 
colorama-0.4.4 idna-2.10 multidict-5.1.0 requests-2.25.1 soupsieve-2.1 
typing-extensions-3.7.4.3 urllib3-1.26.2 yarl-1.6.3
```

Is it possible you have something older installed in that environment and it's causing and issue by not upgrading it? Can you try blowing away the venv and trying again?

**Comment by mikeckennedy** [comment]
Hi @bbelderbos ! Thanks for the idea of pinning the requirements. I'd like to use the latest as long as they work. From what I can tell, they are still OK as a group unless I'm missing something in my response above.

**Comment by mikeckennedy** [comment]
I wonder if I'm using a newer pip for this? @johniuro Can you check your version and see if it's the latest?

```
$ pip -V
pip 20.3.3 from /Users/michaelkennedy/Desktop/z/venv/lib/python3.9/site-packages/pip (python 3.9)
```

If it's not, try a fresh venv with it updated.

**Comment by bbelderbos** [comment]
Confirmed on my end: `pip install --upgrade pip` and the `pip install` runs clean / without error.

**Comment by mikeckennedy** [comment]
Fantastic, thank you Bob!
