### ISSUE TITLE
Breaking changes apistar from 0.5.41 to 0.6+ 

### ISSUE THREAD

**Issue by ericchou1** [talkpython/100daysofweb-with-python-course#5]
Hi, looks like the latest version of apistar (apistar==0.7.2) did away with some features that prohibits the 'from apistar import App' from working. From http://docs.apistar.com/:

Where did the server go?
With version 0.6 onwards the API Star project is being focused as a framework-agnositic suite of API tooling. The plan is to build out this functionality in a way that makes it appropriate for use either as a stand-alone tool, or together with a large range of frameworks.

The 0.5 branch remains available on GitHub, and can be installed from PyPI with pip install apistar==0.5.41. Any further development of the API Star server would likely need to be against a fork of that, under a new maintainer.

Might want to pin down the install version to 0.5.41 in requirements.txt file.

**Comment by mikeckennedy** [comment]
Thanks Eric. I changed the requirement to 

`apistar>=0.5.41,<0.5.1000`

So that we can upgrade for bug fixes, security, etc, but stay in the 0.5 realm.
