### ISSUE TITLE
Day 41 Example Tips Page changed

### ISSUE THREAD

**Issue by johniuro** [talkpython/100daysofweb-with-python-course#57]
Following the course, the page used to grab tips and code from, https://codechalleng.es/tips, has been completely changed. Is there a new url for the old example tips so I can continue the demo? Thank you

**Comment by bbelderbos** [comment]
@johniuro thanks bringing this to our attention! 

I updated the endpoint to https://codechalleng.es/api/tips/ and fixed the `sync_tips.py` script  to work with it (from `BeautifulSoup` to parsing the `requests` response, much nicer!)

While there I fixed another CORS issue and updated the README, I even included a `Makefile` to make the setup easier. I tested the React app locally and it all works for me. Just pull https://github.com/pybites/python_tips again and go through the setup. Hope it works fine for you too now, enjoy the `axios` experience.

HTH
Bob
