### ISSUE TITLE
Days 33-36: broken link

### ISSUE THREAD

**Issue by CaptSolo** [talkpython/100daysofweb-with-python-course#60]
[README file](https://github.com/talkpython/100daysofweb-with-python-course/blob/master/days/033-036-sqlalchemy-orm/your-turn/README.md) for days 033-036 contains a broken link:

[top-18-database-projects-ideas](https://www.lovelycoding.org/2013/11/top-18-database-projects-ideas-for.engineering-bca-mca-btech-bsc.html)

Internet Archive URL can be used instead: https://web.archive.org/web/20200922100027/https://www.lovelycoding.org/2013/11/top-18-database-projects-ideas-for.engineering-bca-mca-btech-bsc.html

**Comment by mikeckennedy** [comment]
That's great that 1) you let me know and 2) that you found the
archive.org version.
Much appreciated and fixed.

Best,
Michael

Sent via Superhuman ***@***.***>
