### ISSUE TITLE
Days 009-012

### ISSUE THREAD

**Issue by vladmonea** [talkpython/100daysofweb-with-python-course#8]
Hi,
Postman PUT doesn't seem to be working. I am changing values for an item and pressing send yet the return is an unchanged json while the console outputs:

127.0.0.1 - - [17/May/2019 21:40:41] "PUT /6 HTTP/1.1" 302 -
127.0.0.1 - - [17/May/2019 21:40:41] "GET /6/ HTTP/1.1" 200 -

I am running the server in Pycharm (community) from the terminal with python app.py

Thanks,
Vlad

**Comment by mikeckennedy** [comment]
Hi Vlad,

I have been hearing that some times you need a trailing backslash on PUT and DELETE there. Try /6/ and see if that works. @bbelderbos  thoughts?

**Comment by bbelderbos** [comment]
Thanks @mikeckennedy, that has happened to me too in the past. I would ned to debug a bit more though to confirm this ...

**Comment by vladmonea** [comment]
Thank you, @mikeckennedy , the trailing backslash did the trick. Might some back end stuff in apistar.
