### ISSUE TITLE
Days 045-048 Build a simple Django app [v20/22] missing messages

### ISSUE THREAD

**Issue by chriskessler** [talkpython/100daysofweb-with-python-course#91]
Hi There,
I noticed once switching to class-based views from function-based, we lost the messages for successful new|update|delete in the video and it wasn't addressed. Any chance that could be touched on? Or maybe I missed something?

Thanks!
Chris

**Comment by bbelderbos** [comment]
Good catch, I did not realize that, thanks!

I abandoned cbvs since ;)

It's hard to update the videos right now, but you can try to use the `SuccessMessageMixin` using this example:
https://dev.to/serhatteker/show-message-in-class-based-views-django-4a4d

HTH
Bob

**Comment by chriskessler** [comment]
Great! Thanks for the links and for the quick response
