### ISSUE TITLE
Day 9 -12: API Star -- Werkzeug Version 3.00 + is not compatible with API Star 0.5.41

### ISSUE THREAD

**Issue by duncanrhardy** [talkpython/100daysofweb-with-python-course#98]
Hey guys! I was running into this issue below when building up the practice API skeleton: 

![image](https://github.com/talkpython/100daysofweb-with-python-course/assets/53665270/fa630062-2929-4eda-ba9b-817d53792c2a)

I think pinning Werkzeug version == 2.3.8 in requirements.txt would be helpful.

![image](https://github.com/talkpython/100daysofweb-with-python-course/assets/53665270/7c953049-c1cb-4332-aa01-be24c65b6401)

**Comment by mikeckennedy** [comment]
Hi @duncanrhardy Thanks for the heads up. Werkzeug did make some breaking changes (not really sure why). I'll have look.

**Comment by mikeckennedy** [comment]
We just updated that chapter. It was API Star (obviously). But since API Star is defunct, I swapped it to FastAPI. Have a look if you're interested in FastAPI. I'm closing this because it no longer applies. Thanks for submitting it.

**Comment by bbelderbos** [comment]
Thanks so much Mike 🙏 😍, much more up2date and better!
